import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Next.js | Wandoledzep",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-5xl mx-auto">
          <nav className="flex gap-8 py-4 border-b border-gray-100 mb-8">
            <Link href="/">Home</Link>
            <Link href="/users">Users</Link>
            <Link href="/bands">Bands</Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
