import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next.js | Wandoledzep",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-5xl mx-auto">
          <nav className="flex gap-8 py-4 border-b border-gray-100 mb-8">
            <Link href="/">Home</Link>
            <Link href="/users">Users</Link>
            <Link href="/bands">Bands</Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
